### PR TITLE
merge

### PR DESCRIPTION
**Pull request by szefo09**

### CODE REVIEW

**Comment by Hello23-Ygopro** [comment]
@szefo09 
I have an idea to improve the mod where you don't have to tap mana cards by banishing them face-down anymore, and they would remain in Yugioh's graveyard zone. Some functions will have to be updated.

<details>
        <summary>Duel functions to be updated</summary>

```lua
--new code for RegisterFlagEffect: DM_EFFECT_MANA_TAPPED
--new desc for RegisterFlagEffect: DM_DESC_TAPPED
function Duel.Tap(targets,reason)
	if type(targets)=="Card" then targets=Group.FromCards(targets) end
	local ct=0
	for tc in aux.Next(targets) do
		if tc:IsAbleToTap() then
			if tc:IsLocation(LOCATION_MZONE) then
				ct=ct+Duel.ChangePosition(tc,POS_FACEUP_TAPPED,reason)
			elseif tc:IsLocation(LOCATION_GRAVE) then
				--add unique flag effect instead of banishing face-down
				tc:RegisterFlagEffect(DM_EFFECT_MANA_TAPPED,RESET_EVENT+RESETS_STANDARD,EFFECT_FLAG_CLIENT_HINT,1,0,DM_DESC_TAPPED)
				ct=ct+1
			end
		end
	end
	return ct
end
function Duel.Untap(targets,reason)
	if type(targets)=="Card" then targets=Group.FromCards(targets) end
	local ct=0
	for tc in aux.Next(targets) do
		if tc:IsAbleToUntap() then
			if tc:IsLocation(LOCATION_MZONE) then
				ct=ct+Duel.ChangePosition(tc,POS_FACEUP_UNTAPPED,reason)
			elseif tc:IsLocation(LOCATION_GRAVE) then
				--remove unique flag effect instead of sending to ygo gy zone
				tc:ResetFlagEffect(DM_EFFECT_MANA_TAPPED)
				ct=ct+1
			end
		end
	end
	return ct
end
```
</details>
<details>
        <summary>Card functions to be updated</summary>

```lua
--new code for GetFlagEffect: DM_EFFECT_MANA_TAPPED
function Card.IsTapped(c)
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsDefensePos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		--check for unique flag effect
		return c:GetFlagEffect(DM_EFFECT_MANA_TAPPED)>0
	end
	return false
end
function Card.IsUntapped(c)
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsAttackPos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		--check for unique flag effect
		return c:GetFlagEffect(DM_EFFECT_MANA_TAPPED)==0
	end
	return false
end
function Card.IsAbleToTap(c)
	if c:IsHasEffect(EFFECT_CANNOT_CHANGE_POS_E) then return false end
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsAttackPos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		return true --removed c:IsAbleToRemove()
	end
	return false
end
function Card.IsAbleToUntap(c)
	if c:IsHasEffect(EFFECT_CANNOT_CHANGE_POS_E) then return false end
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsDefensePos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		return true --removed c:IsAbleToGrave()
	end
	return false
end
```
</details>

If correctly implemented, tapped mana cards and Duel Masters graveyard cards won't share the banished zone anymore, making it easier to view them, and I won't have to use filter functions (`dm.ManaZoneFilter` and `dm.DMGraveFilter`) anymore.

But it will be harder to view cards in the mana zone because they will all be face-up and vertical in Yugioh's graveyard zone. I can add a description to the tapped mana cards to help with this, but I don't know if I should implement it mainly because how hard it will be to look at your mana zone when deciding which cards you want to play.

Do you think I should implement this or keep everything the way it is?

**Comment by Hello23-Ygopro** [comment]
@szefo09 
I have an idea to improve the mod where you don't have to tap mana cards by banishing them face-down anymore, and they would remain in Yugioh's graveyard zone. Some functions will have to be updated.

<details>
        <summary>Duel functions to be updated</summary>

```lua
--new code for RegisterFlagEffect: DM_EFFECT_MANA_TAPPED
--new desc for RegisterFlagEffect: DM_DESC_TAPPED
function Duel.Tap(targets,reason)
	if type(targets)=="Card" then targets=Group.FromCards(targets) end
	local ct=0
	for tc in aux.Next(targets) do
		if tc:IsAbleToTap() then
			if tc:IsLocation(LOCATION_MZONE) then
				ct=ct+Duel.ChangePosition(tc,POS_FACEUP_TAPPED,reason)
			elseif tc:IsLocation(LOCATION_GRAVE) then
				--add unique flag effect instead of banishing face-down
				tc:RegisterFlagEffect(DM_EFFECT_MANA_TAPPED,RESET_EVENT+RESETS_STANDARD,EFFECT_FLAG_CLIENT_HINT,1,0,DM_DESC_TAPPED)
				ct=ct+1
			end
		end
	end
	return ct
end
function Duel.Untap(targets,reason)
	if type(targets)=="Card" then targets=Group.FromCards(targets) end
	local ct=0
	for tc in aux.Next(targets) do
		if tc:IsAbleToUntap() then
			if tc:IsLocation(LOCATION_MZONE) then
				ct=ct+Duel.ChangePosition(tc,POS_FACEUP_UNTAPPED,reason)
			elseif tc:IsLocation(LOCATION_GRAVE) then
				--remove unique flag effect instead of sending to ygo gy zone
				tc:ResetFlagEffect(DM_EFFECT_MANA_TAPPED)
				ct=ct+1
			end
		end
	end
	return ct
end
```
</details>
<details>
        <summary>Card functions to be updated</summary>

```lua
--new code for GetFlagEffect: DM_EFFECT_MANA_TAPPED
function Card.IsTapped(c)
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsDefensePos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		--check for unique flag effect
		return c:GetFlagEffect(DM_EFFECT_MANA_TAPPED)>0
	end
	return false
end
function Card.IsUntapped(c)
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsAttackPos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		--check for unique flag effect
		return c:GetFlagEffect(DM_EFFECT_MANA_TAPPED)==0
	end
	return false
end
function Card.IsAbleToTap(c)
	if c:IsHasEffect(EFFECT_CANNOT_CHANGE_POS_E) then return false end
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsAttackPos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		return true --removed c:IsAbleToRemove()
	end
	return false
end
function Card.IsAbleToUntap(c)
	if c:IsHasEffect(EFFECT_CANNOT_CHANGE_POS_E) then return false end
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsDefensePos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		return true --removed c:IsAbleToGrave()
	end
	return false
end
```
</details>

If correctly implemented, tapped mana cards and Duel Masters graveyard cards won't share the banished zone anymore, making it easier to view them, and I won't have to use filter functions (`dm.ManaZoneFilter` and `dm.DMGraveFilter`) anymore.

However, it will be harder to view cards in the mana zone because they will all be face-up and vertical in Yugioh's graveyard zone. I can add a description to the tapped mana cards to help with this, but I don't know if I should implement it mainly because how hard it will be to look at your mana zone when deciding which cards you want to play from your hand.

Do you think I should implement this or keep everything the way it is?

**Comment by Hello23-Ygopro** [comment]
@szefo09 
I have an idea to improve the mod where you don't have to tap mana cards by banishing them face-down anymore, and they would remain in Yugioh's graveyard zone. Some functions will have to be updated.

<details>
        <summary>Duel functions to be updated</summary>

```lua
--new code for RegisterFlagEffect: DM_EFFECT_MANA_TAPPED
--new desc for RegisterFlagEffect: DM_DESC_TAPPED
function Duel.Tap(targets,reason)
	if type(targets)=="Card" then targets=Group.FromCards(targets) end
	local ct=0
	for tc in aux.Next(targets) do
		if tc:IsAbleToTap() then
			if tc:IsLocation(LOCATION_MZONE) then
				ct=ct+Duel.ChangePosition(tc,POS_FACEUP_TAPPED,reason)
			elseif tc:IsLocation(LOCATION_GRAVE) then
				--add unique flag effect instead of banishing face-down
				tc:RegisterFlagEffect(DM_EFFECT_MANA_TAPPED,RESET_EVENT+RESETS_STANDARD,EFFECT_FLAG_CLIENT_HINT,1,0,DM_DESC_TAPPED)
				ct=ct+1
			end
		end
	end
	return ct
end
function Duel.Untap(targets,reason)
	if type(targets)=="Card" then targets=Group.FromCards(targets) end
	local ct=0
	for tc in aux.Next(targets) do
		if tc:IsAbleToUntap() then
			if tc:IsLocation(LOCATION_MZONE) then
				ct=ct+Duel.ChangePosition(tc,POS_FACEUP_UNTAPPED,reason)
			elseif tc:IsLocation(LOCATION_GRAVE) then
				--remove unique flag effect instead of sending to ygo gy zone
				tc:ResetFlagEffect(DM_EFFECT_MANA_TAPPED)
				ct=ct+1
			end
		end
	end
	return ct
end
```
</details>
<details>
        <summary>Card functions to be updated</summary>

```lua
--new code for GetFlagEffect: DM_EFFECT_MANA_TAPPED
function Card.IsTapped(c)
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsDefensePos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		--check for unique flag effect
		return c:GetFlagEffect(DM_EFFECT_MANA_TAPPED)>0
	end
	return false
end
function Card.IsUntapped(c)
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsAttackPos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		--check for unique flag effect
		return c:GetFlagEffect(DM_EFFECT_MANA_TAPPED)==0
	end
	return false
end
function Card.IsAbleToTap(c)
	if c:IsHasEffect(EFFECT_CANNOT_CHANGE_POS_E) then return false end
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsAttackPos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		return true --removed c:IsAbleToRemove()
	end
	return false
end
function Card.IsAbleToUntap(c)
	if c:IsHasEffect(EFFECT_CANNOT_CHANGE_POS_E) then return false end
	if c:IsLocation(LOCATION_MZONE) then
		return c:IsDefensePos()
	elseif c:IsLocation(LOCATION_GRAVE) then
		return true --removed c:IsAbleToGrave()
	end
	return false
end
```
</details>

If correctly implemented, tapped mana cards and Duel Masters graveyard cards won't share the banished zone, making it easier to view them, and I won't have to use filter functions (`dm.ManaZoneFilter` and `dm.DMGraveFilter`) anymore.

However, it will be harder to view cards in the mana zone because they will all be face-up and vertical in Yugioh's graveyard zone. I can add a description to the tapped mana cards to help with this, but I don't know if I should implement it mainly because how hard it will be to look at your mana zone when deciding which cards you want to play from your hand.

Do you think I should implement this or keep everything the way it is?

**Comment by szefo09** [comment]
Hey, you have a pretty interesting idea with all of this. If it's just a matter of visuals and you don't have to redesign the banish face-down (into some other zone in the future?) I would suggest keeping it as is, becase (sorry, but I'll be giving YGOPro2 examples, it may be different in YGOPro):
1) it's feels like that the amount of available mana is a lot more useful than the whole amount of mana you have. (used+free), and thanks to splitting mana like it's currently, you always get the value of available mana.
2) in YGOPro2, the only indication if a card is banished face-down or face-up is a text above the card description, so to check if a card is in GY or in mana-zone used, you already have to do the task you described. 
image

A counter argument is that I've edited the translation.conf file a bit so the zones would be labeled a bit more like in Duel Masters, but I can simply change Graveyard to `Graveyard/Used-up Mana` :
image

**Pull request merged**
