### PR TITLE
merge

### PR DESCRIPTION
**Pull request by szefo09**

### CODE REVIEW

**Comment by Hello23-Ygopro** [comment]
@szefo09
I'm considering adding a new function for effects that check if a player has some cards in a zone. [_Armored Walker Urherion_](https://github.com/Hello23-Ygopro/ygopro-dm/blob/master/expansions/script/c24001067.lua) is an example card with a continuous effect that can use this function and [_Illusionary Merfolk_](https://github.com/Hello23-Ygopro/ygopro-dm/blob/master/expansions/script/c24001032.lua) is an example card with a trigger effect that can use this function:
```lua
function Auxiliary.ExistingCardCondition(f,s,o,count)
	return	function(e,tp,eg,ep,ev,re,r,rp)
				f=f or aux.TRUE
				s=s or DM_LOCATION_BATTLE
				o=o or 0
				count=count or 1
				return Duel.IsExistingMatchingCard(f,tp,s,o,count,nil,e,tp,eg,ep,ev,re,r,rp)
			end
end
```

It will look like this when I include this function for these cards:
`dm.ExistingCardCondition(scard.cfilter)`

Some questions:
1. I could be wrong, but I think `tp` as seen in `Duel.IsExistingMatchingCard` above represents the "trigger player" (the player who triggers the effect) and not the "turn player" as seen in some tutorials, so this function might cause problems for continuous effects. Should I change `tp` to `e:GetHandlerPlayer()`? I'm not too experienced with this...
2. Also do you think I should add more functions like this to shorten more code? Depending on the card, eventually mostly operation functions won't be shortened.
3. Do you know of any more areas in YGOPro-DM that could be shortened?

---
Previous comments:
- https://github.com/szefo09/ygopro-dm/pull/79
- https://github.com/szefo09/ygopro-dm/pull/73
- https://github.com/szefo09/ygopro-dm/pull/64

**Comment by Hello23-Ygopro** [comment]
@szefo09
I'm considering adding a new function for effects that check if a player has some cards in a zone. [_Armored Walker Urherion_](https://github.com/Hello23-Ygopro/ygopro-dm/blob/master/expansions/script/c24001067.lua) is an example card with a continuous effect that can use this function and [_Illusionary Merfolk_](https://github.com/Hello23-Ygopro/ygopro-dm/blob/master/expansions/script/c24001032.lua) is an example card with a trigger effect that can use this function:
```lua
function Auxiliary.ExistingCardCondition(f,s,o,count)
	return	function(e,tp,eg,ep,ev,re,r,rp)
				f=f or aux.TRUE
				s=s or DM_LOCATION_BATTLE
				o=o or 0
				count=count or 1
				return Duel.IsExistingMatchingCard(f,tp,s,o,count,nil,e,tp,eg,ep,ev,re,r,rp)
			end
end
```

It will look like this when I include this function for these cards:
`dm.ExistingCardCondition(scard.cfilter)`

Some questions:
1. I could be wrong, but I think `tp` as seen in `Duel.IsExistingMatchingCard` above represents the "trigger player" (the player who triggers the effect) and not the "turn player" as seen in some tutorials, so this function might cause problems for continuous effects. Should I change `tp` to `e:GetHandlerPlayer()`? I'm not too experienced with this...
2. Also do you think I should add more functions like this to shorten more code? Depending on the card, eventually mostly operation functions won't be shortened.
3. Do you know of any more areas in YGOPro-DM that can be shortened?

---
Previous comments:
- https://github.com/szefo09/ygopro-dm/pull/79
- https://github.com/szefo09/ygopro-dm/pull/73
- https://github.com/szefo09/ygopro-dm/pull/64

**Comment by szefo09** [comment]
I asked people that know scripting a lot better than I do (I have no experience :P )
And what I got is that tp stands for triggering player, as you’ve mentioned.
And for second and third question, I’m not on high enough level to say with certainity if those will be useful. If that means you’ll have to more tools to work with (faster script writing thanks to them) then yeah, sound alright. I just hope you won’t get lost with too many of shortened scripts.

**Comment by Hello23-Ygopro** [comment]
> I just hope you won’t get lost with too many of shortened scripts

That can be a problem, especially if there are many abbreviated names.

I'll try that function. Thanks for the help.

**Pull request merged**
