### PR TITLE
merge new cards

### PR DESCRIPTION
**Pull request by szefo09**

### CODE REVIEW

**Comment by Hello23-Ygopro** [comment]
@szefo09 
I noticed the extra monster zone isn't used. Do you think a rule should be added that checks if all your main monster zones are full, and makes you move one of your creatures to the extra monster zone? This way you can have a total of 6 creatures.

I also thought about using empty spell/trap zones to put creatures in so you can have even more creatures, but this will cause too many problems:
- Moving a card between a monster zone and spell/trap zone makes it lose all effects it gained
- A creature in the spell/trap zone doesn't have the stats of a monster (level, atk, def, etc.)
- A creature in the spell/trap zone can't be attacked, unless a player switches them to the monster zone
- You can't tap a creature in the spell/trap zone
- Summoning and evolving a creature in the spell/trap zone is complicated
- You won't always know if a face-up card in the spell/trap zone is a creature or a shield that was turned face-up

---
Previous comments:
- https://github.com/szefo09/ygopro-dm/pull/73
- https://github.com/szefo09/ygopro-dm/pull/64

**Comment by szefo09** [comment]
@Hello23-Ygopro I think that opening the 6th zone up would be an ok idea.
But as you’ve mentioned putting monsters into spell/trap zones is too much hassle

**Comment by Hello23-Ygopro** [comment]
Here's the rule for opening the extra monster zone for both players:
```lua
--DM_HINTMSG_MOVEZONE = "Select a creature to move to another zone."
--SEQUENCE_MZONE_EX_LEFT = 5
local ex=Effect.CreateEffect(c)
ex:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_IGNORE_IMMUNE+EFFECT_FLAG_SET_AVAILABLE)
ex:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
ex:SetCode(EVENT_ADJUST)
ex:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
	local f=function(c)
		return c:GetSequence()>=5
	end
	if Duel.GetLocationCount(0,LOCATION_MZONE)==0 and not Duel.IsExistingMatchingCard(f,0,LOCATION_MZONE,0,1,nil) then
		Duel.Hint(HINT_SELECTMSG,0,DM_HINTMSG_MOVEZONE)
		local g1=Duel.SelectMatchingCard(0,nil,0,LOCATION_MZONE,0,1,1,nil)
		if g1:GetCount()==0 then return end
		Duel.MoveSequence(g1:GetFirst(),SEQUENCE_MZONE_EX_LEFT)
	end
	if Duel.GetLocationCount(1,LOCATION_MZONE)==0 and not Duel.IsExistingMatchingCard(f,1,LOCATION_MZONE,0,1,nil) then
		Duel.Hint(HINT_SELECTMSG,1,DM_HINTMSG_MOVEZONE)
		local g2=Duel.SelectMatchingCard(1,nil,1,LOCATION_MZONE,0,1,1,nil)
		if g2:GetCount()==0 then return end
		Duel.MoveSequence(g2:GetFirst(),SEQUENCE_MZONE_EX_LEFT)
	end
end)
Duel.RegisterEffect(ex,tp)
```

The only problem is, when you try to evolve a creature in the extra monster zone, you are forced to select a main monster zone to summon the creature in. This is part of master rule 4 - you can only special summon a monster from the extra deck to an extra monster zone.

Do you think it's possible to special summon a monster to an extra monster zone from a non-extra deck location without having to modify the source code?
I tried updating `Duel.SpecialSummon(targets, sumtype, sumplayer, target_player, nocheck, nolimit, pos, zone)` and changing the `zone` value, but I'm not entirely sure how it works, and I'm not sure if it will work for special summons that don't start a chain, like the creature summoning procedures.

**Comment by szefo09** [comment]
Purerosefallen (Sekka’s Koishi) said that a method like that is available on their fork of the core. The method is called `EFFECT_EXTRA_TOMAIN_KOISHI`
I’m currently using Fluoro’s core 0x1349, so I would have to switch to Koishi’s

**Comment by Hello23-Ygopro** [comment]
Thanks for the refferal.

So it doesn't seem possible with Fluoro's core...

One method I've used before is to make each monster a pendulum, which enables them to be added to the extra deck with `Duel.PSendtoExtra` so they can be special summoned to an extra monster zone, but I don't want to go through all that trouble just for an extra zone. For now I'll stick to 5 monster zones per player, until I find a simpler method without changing the source code.

**Pull request merged**
